package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"skillsync/tui/internal/opencode"
	"skillsync/tui/internal/runner"
)

// TestSyncParity verifies that dry-run and real-run modes produce identical skill artifacts.
// This guards against regression where real-run reads stale .opencode instead of .agents source.
// The test creates a temp root with .agents/skills source and a divergent stale .opencode mirror,
// then exercises the real entry point syncOpenCodeForRoot in both DryRun modes.
func TestSyncParity(t *testing.T) {
	tmpRoot := t.TempDir()

	// Fixture Stage 1: Create .agents/skills/test-skill/SKILL.md as the source of truth.
	agentSkillDir := filepath.Join(tmpRoot, ".agents", "skills", "test-skill")
	if err := os.MkdirAll(agentSkillDir, 0755); err != nil {
		t.Fatalf("failed to create .agents skill dir: %v", err)
	}

	skillMD := `---
name: test-skill
description: A test skill for parity verification
---

# Test Skill

This is a test skill.
`
	skillPath := filepath.Join(agentSkillDir, "SKILL.md")
	if err := os.WriteFile(skillPath, []byte(skillMD), 0644); err != nil {
		t.Fatalf("failed to write .agents SKILL.md: %v", err)
	}

	// Fixture Stage 2: Create stale .opencode mirror with divergent skill.
	// This stale skill must NOT appear in either dry-run or real-run output,
	// proving both paths read from .agents source, not the divergent mirror.
	staleSkillDir := filepath.Join(tmpRoot, ".opencode", "skills", "stale-skill")
	if err := os.MkdirAll(staleSkillDir, 0755); err != nil {
		t.Fatalf("failed to create stale .opencode skill dir: %v", err)
	}

	staleSkillMD := `---
name: stale-skill
description: A stale skill that should be pruned
---

# Stale Skill

This should not appear in either dry-run or real-run generated artifacts.
`
	staleSkillPath := filepath.Join(staleSkillDir, "SKILL.md")
	if err := os.WriteFile(staleSkillPath, []byte(staleSkillMD), 0644); err != nil {
		t.Fatalf("failed to write stale .opencode SKILL.md: %v", err)
	}

	// Fixture Stage 3: Create stub AGENTS.md so CopyAgentsMD has content to work with.
	stubAgentsMD := `# Agent Skills

## Available Skills

| Skill | Description | Location |
| ----- | ----------- | -------- |
| test-skill | A test skill for parity verification | [SKILL.md](.agents/skills/test-skill/SKILL.md) |

### Auto-invoke Skills

When performing these actions, ALWAYS invoke the corresponding skill FIRST:

| Action | Skill |
| ------ | ----- |
`
	if err := os.WriteFile(filepath.Join(tmpRoot, "AGENTS.md"), []byte(stubAgentsMD), 0644); err != nil {
		t.Fatalf("failed to write stub AGENTS.md: %v", err)
	}

	// Test Stage 1: Exercise real entry point in DRY-RUN mode.
	// This mode should read from .agents source and generate OPENCODE.md plan.
	// Note: Prune:false to keep stale-skill in .opencode mirror so stage 4 discovery
	// would discover it if bug exists (parseMirroredSkills called with DryRun:false).
	dryReport, err := syncOpenCodeForRoot(tmpRoot, opencode.Options{
		DryRun: true,
		Prune:  false,
	})
	if err != nil {
		t.Fatalf("dry-run syncOpenCodeForRoot failed: %v", err)
	}

	// Extract the planned skill-manager.md from the dry-run report.
	// This file is generated by RegenerateAgent based on discovered skills.
	dryAgentMD := reportChange(dryReport, ".opencode/agents/skill-manager.md")
	if dryAgentMD == "" {
		t.Fatalf("dry-run report missing .opencode/agents/skill-manager.md change")
	}

	// Verify dry-run generated agent references test-skill only (not stale-skill).
	// Dry-run uses syncengine.DiscoverSkills which reads .agents source only.
	if !strings.Contains(dryAgentMD, "test-skill") {
		t.Errorf("dry-run skill-manager.md missing test-skill. Content:\n%s", dryAgentMD)
	}
	if strings.Contains(dryAgentMD, "stale-skill") {
		t.Errorf("dry-run skill-manager.md should NOT contain stale-skill (only reads .agents source). Content:\n%s", dryAgentMD)
	}

	// Test Stage 2: Exercise real entry point in REAL mode.
	// This mode should produce identical artifacts to dry-run.
	// Prune:false so that stale-skill orphan survives; if bug exists, parseMirroredSkills
	// will discover both test-skill and stale-skill (diverging from dry-run which discovered only test-skill).
	_, err = syncOpenCodeForRoot(tmpRoot, opencode.Options{
		DryRun: false,
		Prune:  false,
	})
	if err != nil {
		t.Fatalf("real-run syncOpenCodeForRoot failed: %v", err)
	}

	// Extract actual skill-manager.md content written by real-run.
	realAgentMDFile, err := os.ReadFile(filepath.Join(tmpRoot, ".opencode", "agents", "skill-manager.md"))
	if err != nil {
		t.Fatalf("failed to read .opencode/agents/skill-manager.md after real-run: %v", err)
	}
	realAgentMD := string(realAgentMDFile)

	// Verify real-run generated agent references test-skill only (not stale-skill).
	// Real-run must use same discovery source as dry-run (after fix: both read .agents).
	// Before fix: real-run would read .opencode, finding both test-skill and stale-skill.
	if !strings.Contains(realAgentMD, "test-skill") {
		t.Errorf("real-run skill-manager.md missing test-skill. Content:\n%s", realAgentMD)
	}
	if strings.Contains(realAgentMD, "stale-skill") {
		t.Errorf("real-run skill-manager.md should NOT contain stale-skill (must read .agents source like dry-run). Content:\n%s", realAgentMD)
	}

	// Parity assertion: Both modes must produce identical skill-manager.md content.
	// This assertion FAILS before the fix (when real-run reads .opencode mirror).
	// After the fix (when both read .agents source), this assertion PASSES.
	if dryAgentMD != realAgentMD {
		t.Errorf("parity mismatch: dry-run and real-run generated different skill-manager.md content.\n"+
			"DRY-RUN:\n%s\n\nREAL-RUN:\n%s",
			dryAgentMD, realAgentMD)
	}
}

// reportChange extracts the "After" field (planned/actual content) of a file change from the report.
// Returns empty string if the path is not found.
func reportChange(report *runner.SyncReport, path string) string {
	if report == nil {
		return ""
	}
	for _, change := range report.Changes {
		if change.Path == path {
			return change.After
		}
	}
	return ""
}
